/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GirisController;
import controller.IzinTalepController;
import controller.KabulEdilenIzinController;
import controller.KayitController;
import controller.KullaniciEkraniController;
import java.awt.Dimension;
import java.sql.Date;
import model.GirisModel;
import model.IzinTalepModel;
import model.KullaniciEkraniModel;

/**
 *
 * @author pC2
 */
public class KullaniciEkrani extends javax.swing.JFrame {
    private GirisController girisController = new GirisController();
    private GirisModel girisModel = girisController.getGirisModel();
    private KullaniciEkraniController kullaniciEkraniController = new KullaniciEkraniController();
    private KullaniciEkraniModel kullaniciEkraniModel = kullaniciEkraniController.getKullaniciEkraniModel();
    private KayitController kayitController = new KayitController();
    private IzinTalepController izinBilgileriController = new IzinTalepController();
    private IzinTalepModel izinTalepModel = izinBilgileriController.getIzinTalepModel();
    private KabulEdilenIzinController kabulEdilenIzinController = new KabulEdilenIzinController();
    /**
     * Creates new form KullaniciEkrani
     */
    public KullaniciEkrani() {
        initComponents();
        kullaniciEkraniController.kullaniciBilgileriAyarla();
        girilenAdLabel.setText(kullaniciEkraniModel.getAd());
        girilenSoyadLabel.setText(kullaniciEkraniModel.getSoyad());
        kullaniciEkraniController.bilgileriListele(kullaniciAdiLabel, tcLabel, sifreLabel, adLabel, soyadLabel, cinsiyetLabel, dogumTarihiLabel, sahirLabel, kullaniciEkraniKalanIzinLabel,birimLabel);
        kalanIzinLabel.setText("<html><b>Kalan izin sayisi : "+Integer.toString(kullaniciEkraniModel.getKalanIzin())+"</b></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bilgiGuncelleDialog = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tcField = new javax.swing.JTextField();
        kadiField = new javax.swing.JTextField();
        sifreField = new javax.swing.JTextField();
        adField = new javax.swing.JTextField();
        soyadField = new javax.swing.JTextField();
        dogumField = new javax.swing.JTextField();
        sehirField = new javax.swing.JTextField();
        kayitGuncelleButton = new javax.swing.JButton();
        erkekToggleButton = new javax.swing.JToggleButton();
        kadinToggleButton = new javax.swing.JToggleButton();
        jLabel24 = new javax.swing.JLabel();
        birimField = new javax.swing.JTextField();
        cinsiyetButtonGroup = new javax.swing.ButtonGroup();
        izinTalepDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        izinBaslangicField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        izinBitisField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        takepTamamlaButton = new javax.swing.JButton();
        izinTuruCheckBox = new javax.swing.JComboBox<>();
        izinGunuLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        kalanIzinLabel = new javax.swing.JLabel();
        kabulEdilenIzinlerDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        kabulEdilenIzinJTable = new javax.swing.JTable();
        girilenAdLabel = new javax.swing.JLabel();
        girilenSoyadLabel = new javax.swing.JLabel();
        kabulEdilenIzinlerButton = new javax.swing.JButton();
        bilgilerimiListeleButton = new javax.swing.JButton();
        izinTalepButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kullaniciAdiLabel = new javax.swing.JLabel();
        tcLabel = new javax.swing.JLabel();
        sifreLabel = new javax.swing.JLabel();
        adLabel = new javax.swing.JLabel();
        soyadLabel = new javax.swing.JLabel();
        cinsiyetLabel = new javax.swing.JLabel();
        dogumTarihiLabel = new javax.swing.JLabel();
        sahirLabel = new javax.swing.JLabel();
        kullaniciEkraniKalanIzinLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        birimLabel = new javax.swing.JLabel();
        kabulEdilenIzinlerButton1 = new javax.swing.JButton();
        cikisButton = new javax.swing.JButton();

        jLabel11.setText("Kullanici Adi :");

        jLabel12.setText("Şifre: ");

        jLabel13.setText("Tc No: ");

        jLabel14.setText("Soyad:");

        jLabel15.setText("Ciinsiyet:");

        jLabel16.setText("Ad:");

        jLabel17.setText("Şehir:");

        jLabel18.setText("Doğum Tarihi:");

        kayitGuncelleButton.setText("Bilgilerimi Güncelle");
        kayitGuncelleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kayitGuncelleButtonActionPerformed(evt);
            }
        });

        erkekToggleButton.setText("Erkek");
        erkekToggleButton.setActionCommand("erkek");

        kadinToggleButton.setText("Kadın");
        kadinToggleButton.setActionCommand("kadin");

        jLabel24.setText("Birim :");

        javax.swing.GroupLayout bilgiGuncelleDialogLayout = new javax.swing.GroupLayout(bilgiGuncelleDialog.getContentPane());
        bilgiGuncelleDialog.getContentPane().setLayout(bilgiGuncelleDialogLayout);
        bilgiGuncelleDialogLayout.setHorizontalGroup(
            bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bilgiGuncelleDialogLayout.createSequentialGroup()
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bilgiGuncelleDialogLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bilgiGuncelleDialogLayout.createSequentialGroup()
                                .addComponent(erkekToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kadinToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(soyadField)
                            .addComponent(adField)
                            .addComponent(sifreField)
                            .addComponent(tcField)
                            .addComponent(kadiField)
                            .addComponent(dogumField)
                            .addComponent(sehirField)
                            .addComponent(birimField)))
                    .addGroup(bilgiGuncelleDialogLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(kayitGuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        bilgiGuncelleDialogLayout.setVerticalGroup(
            bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bilgiGuncelleDialogLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kadiField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sifreField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soyadField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(erkekToggleButton)
                        .addComponent(kadinToggleButton))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dogumField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sehirField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bilgiGuncelleDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birimField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(kayitGuncelleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        cinsiyetButtonGroup.add(erkekToggleButton);
        cinsiyetButtonGroup.add(kadinToggleButton);

        jLabel2.setText("Izin Baslangic Tarihi :");

        jLabel19.setText("Izin Bitis Tarihi :");

        jLabel20.setText("Izin Türü :");

        takepTamamlaButton.setText("Talep Tamamla");
        takepTamamlaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takepTamamlaButtonActionPerformed(evt);
            }
        });

        izinTuruCheckBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yillik Izin", "Mazeret Izni", "Raporlu Izin", "Ucretsiz Izin" }));

        izinGunuLabel.setText("izingunu");

        jLabel21.setText("<html><b>yyyy-aa-gg</b></html>");

        jLabel22.setText("<html><b>yyyy-aa-gg</b></html>");

        kalanIzinLabel.setText("Kalanİzin");

        javax.swing.GroupLayout izinTalepDialogLayout = new javax.swing.GroupLayout(izinTalepDialog.getContentPane());
        izinTalepDialog.getContentPane().setLayout(izinTalepDialogLayout);
        izinTalepDialogLayout.setHorizontalGroup(
            izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izinTalepDialogLayout.createSequentialGroup()
                .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(izinTalepDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kalanIzinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(izinTalepDialogLayout.createSequentialGroup()
                        .addGap(26, 49, Short.MAX_VALUE)
                        .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(izinTalepDialogLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(izinBaslangicField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(izinTalepDialogLayout.createSequentialGroup()
                                .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(izinBitisField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(izinTuruCheckBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(izinTalepDialogLayout.createSequentialGroup()
                .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(izinTalepDialogLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(takepTamamlaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(izinTalepDialogLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(izinGunuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        izinTalepDialogLayout.setVerticalGroup(
            izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izinTalepDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(kalanIzinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izinBaslangicField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(izinBitisField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(izinTalepDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(izinTuruCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izinGunuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(takepTamamlaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kabulEdilenIzinJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(kabulEdilenIzinJTable);

        javax.swing.GroupLayout kabulEdilenIzinlerDialogLayout = new javax.swing.GroupLayout(kabulEdilenIzinlerDialog.getContentPane());
        kabulEdilenIzinlerDialog.getContentPane().setLayout(kabulEdilenIzinlerDialogLayout);
        kabulEdilenIzinlerDialogLayout.setHorizontalGroup(
            kabulEdilenIzinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kabulEdilenIzinlerDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        kabulEdilenIzinlerDialogLayout.setVerticalGroup(
            kabulEdilenIzinlerDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kabulEdilenIzinlerDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        girilenAdLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        girilenAdLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        girilenAdLabel.setText("jLabel1");

        girilenSoyadLabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        girilenSoyadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        girilenSoyadLabel.setText("jLabel1");

        kabulEdilenIzinlerButton.setText("Kabul Edilen İzinlerimi Listele");
        kabulEdilenIzinlerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabulEdilenIzinlerButtonActionPerformed(evt);
            }
        });

        bilgilerimiListeleButton.setText("Bilgilerimi Güncelle");
        bilgilerimiListeleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgilerimiListeleButtonActionPerformed(evt);
            }
        });

        izinTalepButton.setText("İzin Talep");
        izinTalepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izinTalepButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TC NO :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ŞİFRE :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AD :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SOYAD :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DOĞUM TARİHİ :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CİNSİYET :");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEHİR :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KALAN İZİN :");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KULLANICI ADI :");

        kullaniciAdiLabel.setForeground(new java.awt.Color(255, 255, 255));

        tcLabel.setForeground(new java.awt.Color(255, 255, 255));

        sifreLabel.setForeground(new java.awt.Color(255, 255, 255));

        adLabel.setForeground(new java.awt.Color(255, 255, 255));

        soyadLabel.setForeground(new java.awt.Color(255, 255, 255));

        cinsiyetLabel.setForeground(new java.awt.Color(255, 255, 255));

        dogumTarihiLabel.setForeground(new java.awt.Color(255, 255, 255));

        sahirLabel.setForeground(new java.awt.Color(255, 255, 255));

        kullaniciEkraniKalanIzinLabel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("BİRİM :");

        birimLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kullaniciAdiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sifreLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(soyadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cinsiyetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dogumTarihiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sahirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kullaniciEkraniKalanIzinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(birimLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullaniciAdiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sifreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soyadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinsiyetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dogumTarihiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sahirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullaniciEkraniKalanIzinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birimLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        kabulEdilenIzinlerButton1.setText("Tum İzinlerimi Listele");
        kabulEdilenIzinlerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kabulEdilenIzinlerButton1ActionPerformed(evt);
            }
        });

        cikisButton.setText("Çıkış");
        cikisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(girilenAdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(girilenSoyadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(izinTalepButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bilgilerimiListeleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kabulEdilenIzinlerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(kabulEdilenIzinlerButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cikisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girilenAdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(girilenSoyadLabel))
                .addGap(5, 5, 5)
                .addComponent(cikisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kabulEdilenIzinlerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bilgilerimiListeleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(izinTalepButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kabulEdilenIzinlerButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bilgilerimiListeleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgilerimiListeleButtonActionPerformed
        kullaniciEkraniController.bilgileriListele(kadiField, tcField, sifreField, adField, soyadField, cinsiyetButtonGroup, dogumField, sehirField, kullaniciEkraniKalanIzinLabel, birimField);
        bilgiGuncelleDialog.setLocation(120, 120);
        bilgiGuncelleDialog.setMinimumSize(new Dimension(330, 500));
        bilgiGuncelleDialog.setVisible(true);        // TODO add your handling code here:
        
    }//GEN-LAST:event_bilgilerimiListeleButtonActionPerformed

    private void kayitGuncelleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kayitGuncelleButtonActionPerformed
        kullaniciEkraniController.guncellemeKontrol(kayitController.seciliDugmeleriAl(cinsiyetButtonGroup), adField, soyadField, kadiField, sifreField, tcField, sehirField, dogumField, birimField);
        if(!(kullaniciEkraniController.getKullaniciEkraniModel().getGuncellemedeHata())){
            kullaniciEkraniController.guncellemeYap();
            kullaniciEkraniController.bilgileriListele(kullaniciAdiLabel, tcLabel, sifreLabel, adLabel, soyadLabel, cinsiyetLabel, dogumTarihiLabel, sahirLabel, kullaniciEkraniKalanIzinLabel, birimLabel);
            bilgiGuncelleDialog.dispose();
        }
    }//GEN-LAST:event_kayitGuncelleButtonActionPerformed

    private void izinTalepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izinTalepButtonActionPerformed
        izinTalepDialog.setLocation(120, 120);
        izinTalepDialog.setMinimumSize(new Dimension(400, 300));
        izinTalepDialog.setVisible(true); 
    }//GEN-LAST:event_izinTalepButtonActionPerformed

    private void takepTamamlaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takepTamamlaButtonActionPerformed
        izinBilgileriController.izinBilgileriKontrolEt(izinBaslangicField, izinBitisField, izinTuruCheckBox.getSelectedItem().toString());
        if(!(izinTalepModel.getBilgilerdeHata())){
            izinBilgileriController.talebiTamamla(izinBaslangicField, izinBitisField, izinGunuLabel);
            izinTalepDialog.dispose();
        }
    }//GEN-LAST:event_takepTamamlaButtonActionPerformed

    private void kabulEdilenIzinlerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabulEdilenIzinlerButtonActionPerformed
        if(girisModel.getGiris())
            kabulEdilenIzinJTable.setModel(kabulEdilenIzinController.tabloModelGetir());
        kabulEdilenIzinlerDialog.setLocation(120, 120);
        kabulEdilenIzinlerDialog.setMinimumSize(new Dimension(1000, 400));
        kabulEdilenIzinlerDialog.setVisible(true);
    }//GEN-LAST:event_kabulEdilenIzinlerButtonActionPerformed

    private void kabulEdilenIzinlerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kabulEdilenIzinlerButton1ActionPerformed
        kabulEdilenIzinJTable.setModel(kabulEdilenIzinController.tumIzinlerTabloModelGetir());
        kabulEdilenIzinlerDialog.setLocation(120, 120);
        kabulEdilenIzinlerDialog.setMinimumSize(new Dimension(800, 400));
        kabulEdilenIzinlerDialog.setVisible(true);
    }//GEN-LAST:event_kabulEdilenIzinlerButton1ActionPerformed

    private void cikisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikisButtonActionPerformed
        AnaEkran anaEkran = new AnaEkran();
        anaEkran.show();
        this.dispose();
    }//GEN-LAST:event_cikisButtonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adField;
    private javax.swing.JLabel adLabel;
    private javax.swing.JDialog bilgiGuncelleDialog;
    private javax.swing.JButton bilgilerimiListeleButton;
    private javax.swing.JTextField birimField;
    private javax.swing.JLabel birimLabel;
    private javax.swing.JButton cikisButton;
    private javax.swing.ButtonGroup cinsiyetButtonGroup;
    private javax.swing.JLabel cinsiyetLabel;
    private javax.swing.JTextField dogumField;
    private javax.swing.JLabel dogumTarihiLabel;
    private javax.swing.JToggleButton erkekToggleButton;
    private javax.swing.JLabel girilenAdLabel;
    private javax.swing.JLabel girilenSoyadLabel;
    private javax.swing.JTextField izinBaslangicField;
    private javax.swing.JTextField izinBitisField;
    private javax.swing.JLabel izinGunuLabel;
    private javax.swing.JButton izinTalepButton;
    private javax.swing.JDialog izinTalepDialog;
    private javax.swing.JComboBox<String> izinTuruCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kabulEdilenIzinJTable;
    private javax.swing.JButton kabulEdilenIzinlerButton;
    private javax.swing.JButton kabulEdilenIzinlerButton1;
    private javax.swing.JDialog kabulEdilenIzinlerDialog;
    private javax.swing.JTextField kadiField;
    private javax.swing.JToggleButton kadinToggleButton;
    private javax.swing.JLabel kalanIzinLabel;
    private javax.swing.JButton kayitGuncelleButton;
    private javax.swing.JLabel kullaniciAdiLabel;
    private javax.swing.JLabel kullaniciEkraniKalanIzinLabel;
    private javax.swing.JLabel sahirLabel;
    private javax.swing.JTextField sehirField;
    private javax.swing.JTextField sifreField;
    private javax.swing.JLabel sifreLabel;
    private javax.swing.JTextField soyadField;
    private javax.swing.JLabel soyadLabel;
    private javax.swing.JButton takepTamamlaButton;
    private javax.swing.JTextField tcField;
    private javax.swing.JLabel tcLabel;
    // End of variables declaration//GEN-END:variables
}
